In [10]:
import pandas as pd
import numpy as np

In [12]:
a= np.ones(3)

In [13]:
a1= np.empty(5)

In [21]:
a2=np.ones([3,2])

b= np.zeros((5,5))

In [16]:
a3=np.full(5,4)
a3

array([4, 4, 4, 4, 4])

In [43]:
a4= np.random.random([3,4])
b3= np.random.random((5,2))
c3= np.random.rand(3,4)

#print(a4)
#print(c3)

In [27]:
a.shape

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
e=np.array([[10,11,12],[13,14,15],[15,16,17],[18,19,20]])

e.shape

(4, 3)

In [19]:
arr= [6,7,8,9]

ar= np.array(arr)

print(type(ar))

<class 'numpy.ndarray'>


In [35]:
print(b.ndim)


2


### Reshapping an array

In [41]:
x= np.arange(36).reshape(9,-1)

x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

#### Common Functions

In [ ]:
sum(), mean(), std(), corrcoef(), min() 

### Indexing

In [54]:
c= np.array([[9,8,7],[1,2,3]], dtype=float)

d= np.array([[4,5,6],[9,8,7]])

In [55]:
c**2

array([[81., 64., 49.],
       [ 1.,  4.,  9.]])

In [57]:
d[0]

array([4, 5, 6])

In [58]:
d[0,2]

6

In [66]:
e=np.arange(10,22).reshape(4,-1)
e

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [71]:
e[:3,:2]

array([[10, 11],
       [13, 14],
       [16, 17]])

In [72]:
e[[2,0,3,1],[2,1,0,2]]

array([18, 11, 19, 15])

In [75]:
e[e>15]

array([16, 17, 18, 19, 20, 21])

### File input and output with arrays

Numpy arrays can be loaded from and saved to binary files with .npy as the extension using load() and save() respectively. This can also be done with text files with text files using loadtxt() and savetxt().

In [11]:
data_csv=pd.read_csv('dataset.csv')

data_csv

record_id  utility_id_ferc1  report_year  \
0        f1_fuel_1994_12_1_0_7                 1         1994   
1       f1_fuel_1994_12_1_0_10                 1         1994   
2        f1_fuel_1994_12_2_0_1                 2         1994   
3        f1_fuel_1994_12_2_0_7                 2         1994   
4       f1_fuel_1994_12_2_0_10                 2         1994   
...                        ...               ...          ...   
29518  f1_fuel_2018_12_12_0_13                12         2018   
29519   f1_fuel_2018_12_12_1_1                12         2018   
29520  f1_fuel_2018_12_12_1_10                12         2018   
29521  f1_fuel_2018_12_12_1_13                12         2018   
29522  f1_fuel_2018_12_12_1_14                12         2018   

           plant_name_ferc1 fuel_type_code_pudl fuel_unit  fuel_qty_burned  \
0                  rockport                coal       ton        5377489.0   
1      rockport total plant                coal       ton       10486945.0   
2                    gorgas                coal       ton        2978683.0   
3                     barry                coal       ton        3739484.0   
4                 chickasaw                 gas       mcf          40533.0   
...                     ...                 ...       ...              ...   
29518    neil simpson ct #1                 gas       mcf          18799.0   
29519  cheyenne prairie 58%                 gas       mcf         806730.0   
29520     lange ct facility                 gas       mcf         104554.0   
29521       wygen 3 bhp 52%                coal       ton         315945.0   
29522       wygen 3 bhp 52%                 gas       mcf          17853.0   

       fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
0                   16.590                      18.59   
1                   16.592                      18.58   
2                   24.130                      39.72   
3                   23.950                      47.21   
4                    1.000                       2.77   
...                    ...                        ...   
29518                1.059                       4.78   
29519                1.050                       3.65   
29520                1.060                       4.77   
29521               16.108                       3.06   
29522                1.059                       0.00   

       fuel_cost_per_unit_delivered  fuel_cost_per_mmbtu  
0                             18.53                1.121  
1                             18.53                1.120  
2                             38.12                1.650  
3                             45.99                1.970  
4                              2.77                2.570  
...                             ...                  ...  
29518                          4.78                9.030  
29519                          3.65                6.950  
29520                          4.77                8.990  
29521                         14.76                1.110  
29522                          0.00               11.680  

[29523 rows x 11 columns]