## Importing Numpy

In [22]:
import numpy as np

In [4]:
arr= np.empty(5)
arr

array([8.60783757e-283, 2.02660700e-315, 9.37395238e-280, 1.72998133e-260,
       8.03810535e+168])

In [5]:
arr.sum()

8.038105351914946e+168

In [8]:
b=np.array([[1,2,3], [4,5,6], [7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Reshapping an array

In [21]:
x= np.arange(36).reshape(9,-1)

x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

In [37]:
a=np.random.rand(3,4)
a

array([[0.5739032 , 0.9293042 , 0.61887018, 0.48593849],
       [0.09664569, 0.35007381, 0.45613367, 0.77465267],
       [0.48350023, 0.45119889, 0.0584523 , 0.37120344]])